version: '3'
services:
    backend:
        image: 993745280062.dkr.ecr.ap-northeast-1.amazonaws.com/backend:latest
        container_name: backend
        env_file:
            - ./backend/.env
        ports:
            - "3000:3000"
        networks:
            - gin-react-mysql
    frontend:
        image: 993745280062.dkr.ecr.ap-northeast-1.amazonaws.com/frontend:latest
        container_name: frontend
        ports:
            - "80:80"
        networks:
            - gin-react-mysql
        links:
            - backend
    database:
        image: 993745280062.dkr.ecr.ap-northeast-1.amazonaws.com/database:latest
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: qwe123
            MYSQL_DATABASE: fullcalendar
            MYSQL_USER: user
            MYSQL_PASSWORD: qwe123
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
        links:
            - backend
        networks:
            - gin-react-mysql
networks:
    gin-react-mysql: