version: '3'
services:
    backend:
        build: ./backend
        container_name: backend
        tty: true
        env_file:
            - ./backend/.env
        volumes:
            - ./backend/app:/go/src/app
        ports:
            - "3000:3000"
    frontend:
        build: ./frontend
        container_name: frontend
        tty: true
        volumes:
            - ./frontend/fullcalendar:/usr/src/app/fullcalendar
        ports:
            - "80:8080"
    database:
        build: ./database
        container_name: database
        volumes:
            - ./database/mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./database/mysql/conf.d:/etc/mysql/conf.d
            - ./database/mysql/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: ${TZ}
        ports:
            - 3306:3306
        links:
            - backend
