FROM golang:1.18.1-bullseye

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    g++ \
    gcc \
    libc6-dev \
    make \
    pkg-config

RUN mkdir /go/src/app
COPY ./app /go/src/app
WORKDIR /go/src/app

RUN go mod tidy

COPY ./docker-entrypoint-ecs.sh /tmp
CMD ["/tmp/docker-entrypoint-ecs.sh"]